set-option -sg escape-time 10
set-option -g focus-events on
# set -g default-command /usr/local/bin/fish
# set -g default-terminal "tmux-256color"

# =====================================================================
# CLIPBOARD & OSC 52 CONFIGURATION FOR SLURM CLUSTER
# =====================================================================
set -g set-clipboard on
set -g allow-passthrough on
# =====================================================================

# unbind prev split binds
unbind %
unbind '"'

#new split binds
bind | split-window -h
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

# Keybindings to pipe the selection to the OSC 52 clipboard handler
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

#list of tmux plugins
# set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' #persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' #automatically saves sessions for you every 15 mins

set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_transparent 1 # transparent background
set -g @tokyo-night-tmux_show_git 1             # local git status
set -g @tokyo-night-tmux_show_wbg 1             # GitHub / GitLab stats
set -g @tokyo-night-tmux_show_netspeed 0        # network speed
set -g @tokyo-night-tmux_show_battery_widget 0  # battery level
set -g @tokyo-night-tmux_show_music 0           # now playing
set -g @tokyo-night-tmux_show_path 1            # current path
set -g @tokyo-night-tmux_show_hostname 1        # machine hostname
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'off'
#initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
