#!/bin/sh

check_vol() {
vol_in_decimal=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk {'print $2'})
volume=$(perl -e "print $vol_in_decimal * 100")
}

down() {
wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-
check_vol
[$volume -gt 0 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
canberra-gtk-play -i audio-volume-change -d "changevolume"
}

up() {
wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+
check_vol
[ $volume -lt 100 ] && volume=`expr $volume`  
dunstify -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
canberra-gtk-play -i audio-volume-change -d "changevolume"
}

mute() {
  wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
