# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

#Monitor setup
# monitor = HDMI-A-1, 3840x2160@60,0x0, 1.5
# monitor = eDP-1, 1920x1080@120,-1600x100, 1.2
# monitor = DP-1, 1680x1050@59.95, 2560x-100, 1, transform, 1
$mainMod = Meta
general {
    layout = scrolling
}

scrolling {
        column_width = 0.3            # Default width of a column (0.1 to 1.0)
        direction = right             # Direction new windows appear (left/right/up/down)
        fullscreen_on_one_column = true # Single columns span the entire screen
        focus_fit_method = 1          # 0 = center on focus, 1 = fit into view
}
# Move the layout view (scroll left/right)
bind = $mainMod, ], layoutmsg, move +col
bind = $mainMod, [, layoutmsg, move -col

# Resize the current column width
bind = $mainMod SHIFT, right, layoutmsg, colresize +0.05
bind = $mainMod SHIFT, left, layoutmsg, colresize -0.05

# Move a window to its own new column (Promote)
bind = $mainMod, P, layoutmsg, promote

# Swap columns
bind = $mainMod CTRL, L, layoutmsg, swapcol r
bind = $mainMod CTRL, H, layoutmsg, swapcol l

xwayland {
  force_zero_scaling = true
}
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = compose:ralt,caps:escape_shifted_capslock
    kb_rules =
    repeat_rate = 50
    repeat_delay = 240
    touchpad {
        natural_scroll = yes
        drag_3fg = 1
    }
}

group {
    groupbar {
        blur = true
    }
}

decoration {
    blur {
        # size = 3
        passes = 3
    }
}
